config/routes.rb
ChicagoTeenMuseum::Application.routes.draw do

  root to: 'galleries#index'

  resources :users, :artworks, :galleries
  resources :comments, only: :create

  get '/about' => 'high_voltage/pages#show', id: 'about'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Artwork, Comment, Gallery, User]

    if user
      can :create, [Artwork, Comment], user_id: user.id

      if user.admin?
        can :create, Gallery
        can [:update, :destroy], :all
      else
        can [:update, :destroy], Artwork, user_id: user.id
        can [:update, :destroy], User, id: user.id
      end
    else
      can :create, User, role: 'normal'
    end
  end
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :galleries, order: :title
  has_many :comments, order: :created_at

  has_attached_file :asset, styles: { thumb: '275' }
  before_post_process :image?

  validates :user, presence: true
  validates :title, presence: true
  validates_attachment :asset, presence: true, size: { in: 0..3.megabytes }

  attr_accessible :title, :asset, :description, :gallery_ids

  scope :in_gallery, lambda {|gallery_id|
    gallery_id = gallery_id.id if gallery_id.is_a?(Gallery)
    joins(:galleries).where('artworks_galleries.gallery_id' => gallery_id)
  }

  def image?
    asset_content_type.starts_with?('image')
  end

  def thumb_url
    asset.url(:thumb)
  end

  def similar
    user.artworks.where('id <> ?', id)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :artwork

  validates :user, presence: true
  validates :artwork, presence: true
  validates :body, presence: true

  attr_accessible :body, :artwork, :artwork_id
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  default_scope order(:title)
  has_and_belongs_to_many :artworks, order: 'created_at DESC'

  validates :title, presence: true

  attr_accessible :title, :description

  def thumb_url
    @thumb_url ||= artworks.last.try(:thumb_url) || 'thumb_placeholder.png'
  end

  def to_s
    title
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  ADMIN_ROLE = 'admin'

  has_many :artworks, order: 'created_at DESC'
  has_many :comments, order: 'created_at DESC'

  attr_accessible :email, :name, :biography, :birthday

  def admin?
    self.role == ADMIN_ROLE
  end

  def to_s
    @display_name ||= name.present? ? name : "Anonymous (#{id})"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    if signed_in?
      raise
    else
      authorize # via Clearance (think of as `authenticate`)
    end
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  def index
    @artworks = @artworks.includes(:comments => :user).page(params[:page])

    if params[:user]
      @artworks = @artworks.where(user_id: params[:user])
      @user = User.find(params[:user])
    end

    if params[:gallery]
      @artworks = @artworks.in_gallery(params[:gallery])
      @gallery = Gallery.find(params[:gallery])
    end

    respond_with(@artworks)
  end

  def create
    @artwork.save
    respond_with(@artwork)
  end

  def update
    @artwork.assign_attributes(params[:artwork])
    # NOTE load_and_authorize_resource doesn't load gallery_ids during
    #  an update like it does during a create
    @artwork.save && (@artwork.gallery_ids = params[:artwork][:gallery_ids])
    respond_with(@artwork)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  def create
    @comment.user = current_user
    @comment.save
    redirect_to artwork_path(@comment.artwork_id)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  def index
    # TODO eagerly load latest artworks (for thumbnails)
    @galleries = @galleries.page(params[:page])
    respond_with(@galleries)
  end

  def create
    @gallery.save
    respond_with(@gallery)
  end

  def update
    @gallery.assign_attributes(params[:gallery])
    @gallery.save
    respond_with(@gallery)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  load_and_authorize_resource except: [:new, :create]
  authorize_resource only: [:new, :create]
  respond_to :html

  def update
    @user.update_attributes(params[:user])
    @user.save
    respond_with(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_form.html.haml
= semantic_form_for @artwork do |f|
  = f.inputs do
    = f.input :title
    = f.input :description
    = f.input :asset, label: 'Image File'
  = f.inputs name: 'Include My Art In These Galleries' do
    = f.input :galleries, as: :check_boxes, label: false
  = f.actions

app/views/artworks/edit.html.haml
%h1 Edit Artwork

= render 'form'

app/views/artworks/index.html.haml
%p.exhibit-tally
  Exhibiting
  %span.count= pluralize(@artworks.total_count, 'Work')
  - if @user
    by
    = link_to @user, user_path(@user)
  - if @gallery
    in gallery
    = link_to @gallery, gallery_path(@gallery)

= render 'shared/thumbs', models: @artworks, max_comments: 5

= paginate @artworks

app/views/artworks/new.html.haml
%h1 New Artwork

= render 'form'

app/views/artworks/show.html.haml
%h1.name= @artwork.title

- if can?(:update, @artwork)
  = link_to 'Edit Artwork', edit_artwork_path(@artwork), class: 'action'

.image-container
  = link_to image_tag(@artwork.asset.url), @artwork.asset.url
  &nbsp;

.byline
  by
  = link_to @artwork.user
  %span.timestamp
    Posted
    = distance_of_time_in_words_to_now @artwork.created_at
    ago

.description
  :markdown
    #{@artwork.description}


.feedback
  - if can?(:create, Comment)
    = semantic_form_for Comment.new(artwork: @artwork) do |f|
      = f.inputs do
        = f.input :artwork_id, as: :hidden
        = f.input :body, label: false
        = f.submit 'Leave A Comment', disable_with: 'Submitting...'


  %ul.comments
    - @artwork.comments.each do |c|
      - anchor = "comment-#{c.id}"
      %li{ id: anchor }
        .byline
          = link_to c.user
          said
          %span.timestamp
            = link_to "#{distance_of_time_in_words_to_now(c.created_at)} ago", "##{anchor}"
        .body
          :markdown
            #{c.body}

- if @artwork.similar.any?
  .more-artwork
    %h3= link_to "More by #{@artwork.user}", artworks_path(user: @artwork.user)
    = render 'shared/thumbs', models: @artwork.similar.limit(3)

app/views/galleries/_form.html.haml
= semantic_form_for @gallery do |f|
  = f.inputs
  = f.actions

app/views/galleries/edit.html.haml
%h1 Edit Gallery

= render 'form'

app/views/galleries/index.html.haml
%p.exhibit-tally
  Exhibiting
  %span.count= pluralize(@galleries.total_count, 'Gallery')

= render 'shared/thumbs', models: @galleries

= paginate @galleries

app/views/galleries/new.html.haml
%h1 New Gallery

= render 'form'

app/views/galleries/show.html.haml
%h1= @gallery.title

- if can?(:update, @gallery)
  = link_to 'Edit Gallery', edit_gallery_path(@gallery), class: 'action'

.description
  :markdown
    #{@gallery.description}

- if @gallery.artworks.any?
  %h2= link_to 'Recent Additions', artworks_path(gallery: @gallery)

  = render 'shared/thumbs', models: @gallery.artworks.limit(9)

app/views/layouts/application.html.haml
%html
  %head
    %title= page_title(app_name: 'Chicago Teen Museum')
    = stylesheet_link_tag 'application' #, cache: true
    = javascript_include_tag 'application' #, cache: true
    = csrf_meta_tags

  %body{class: body_class}
    .header-outer
      %header
        %nav.account
          = link_to image_tag('logo_small.png'), root_path, class: 'logo'
          = link_to 'About Us', about_path
          - if signed_in?
            = link_to 'Your Profile', (signed_in? ? current_user : sign_in_path)
            = link_to 'Sign Out', sign_out_path, method: :delete
          - else
            = link_to 'Join Us!', sign_up_path, class: 'call-to-action'
            = link_to 'Sign In', sign_in_path
        %nav.content
          = link_to 'Galleries', galleries_path
          - if can?(:create, Gallery)
            = link_to 'Create A Gallery!', new_gallery_path
          = link_to 'Artwork', artworks_path
          = link_to 'Post Your Artwork!', new_artwork_path, class: 'call-to-action'

    .content-outer
      .content
        = yield

    .footer-outer
      %footer

app/views/pages/about.html.haml
- content_for :extra_body_classes, 'about-page'

.col
  %h1 Our Mission

  %p Chicago Teen Museum is the first museum dedicated entirely to the preservation of teen culture by connecting youth expression to the museum profession.

  %h1 Our Vision

  %p Chicago Teen Museum is committed to serving as a consortium for all things teen-related within the Chicagoland community.

.col
  %h1 Our Goals

  %ul
    %li Empower teens to present a strong and positive image
    %li Enhance teen growth and development both artistically and professionally
    %li Foster a positive understanding of teen culture while cultivating a respect and understanding for museums
    %li Increase the public's understanding of "teen culture" through exhibits, programs, partnerships and research
    %li Provide opportunities for educators, parents, and teens to develop a greater sense of identity
    %li Enhance research of teen culture through study of and collaboration with teens

app/views/pages/home.html.haml
- content_for :extra_body_classes, 'about-page'

.col
  %h1 Our Mission

  %p Chicago Teen Museum is the first museum dedicated entirely to the preservation of teen culture by connecting youth expression to the museum profession.

  %h1 Our Vision

  %p Chicago Teen Museum is are committed to serving as a consortium for all things teen-related within the Chicagoland community.

.col
  %h1 Our Goals

  %ul
    %li Empower teens to present a strong and positive image
    %li Enhance teen growth and development both artistically and professionally
    %li Foster a positive understanding of teen culture while cultivating a respect and understanding for museums
    %li Increase the public's understanding of "teen culture" through exhibits, programs, partnerships and research
    %li Provide opportunities for educators, parents, and teens to develop a greater sense of identity
    %li Enhance research of teen culture through study of and collaboration with teens

app/views/shared/_thumbs.html.haml
- models ||= []
- max_comments ||= 0

%ul.thumbs
  - models.each do |m|
    %li.thumb
      .image-container
        = link_to image_tag(m.thumb_url), m
      .caption= link_to m.title, m
      - if max_comments > 0
        %ul.comments
          - m.comments.limit(max_comments).each do |c|
            %li
              = link_to c.user, c.user, class: 'commenter'
              = truncate(c.body, length: 80)

app/views/users/edit.html.haml
= semantic_form_for @user do |f|
  = f.inputs :email, :name, :biography
  = f.actions

app/views/users/show.html.haml
%h1.name= @user

- if can?(:update, @user)
  = link_to 'Edit Profile', edit_user_path(@user), class: 'action'

.biography
  :markdown
    #{@user.biography}

- if @user.artworks.any?
  %h2= link_to 'Recent Artwork', artworks_path(user: @user)

  - if @user == current_user && can?(:create, Artwork)
    = link_to 'Post Artwork', new_artwork_path, class: 'action'

  = render 'shared/thumbs', models: @user.artworks.limit(9)